import numpy as n
a=n.array([54,56,78,87,28,67])
print("An array:",a)
print("product:",n.prod(a))
print("mean:",n.mean(a))
print("standard deviation:",n.std(a))
print("varient",n.var(a))
print("minimum value:",n.min(a))
print("maximum value:",n.max(a))
print("min index",n.argmin(a))
print(" value:",n.argmax(a))
print("minimum index:",n.min(a))
print("minimum index:",n.min(a))
print("median:",n.median(a))
print("product:",n.prod(a))